# Generated by Django 3.1.5 on 2021-01-19 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('balance', models.IntegerField(verbose_name='Баланс')),
                ('hold', models.IntegerField(verbose_name='Холд')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
            ],
        ),
    ]
